apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: index.docker.io/sshjavi/go-devsecops-api
    newName: index.docker.io/sshjavi/go-devsecops-api
    newTag: 108397074efbfc4bb948f9b56ff378cfd2ef3155
